# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_View(object):
    def setupUi(self, View):
        View.setObjectName("View")
        View.resize(1200, 824)
        View.setStyleSheet("QWidget#centralwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(66, 66, 66, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.centralwidget = QtWidgets.QWidget(View)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(330, 20, 540, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        self.title.setFont(font)
        self.title.setStyleSheet("")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.clock_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clock_btn.setGeometry(QtCore.QRect(1070, 740, 120, 50))
        self.clock_btn.setStyleSheet("QPushButton#clock_btn{\n"
"border-radius:20;\n"
"background-color: rgb(94, 94, 94);\n"
"color:rgb(235, 235, 235);\n"
"font: 700 20pt \"Arial\";\n"
"}\n"
"QPushButton#clock_btn:pressed{\n"
"border-style:solid;\n"
"border-width:2px;\n"
"}")
        self.clock_btn.setObjectName("clock_btn")
        self.inst_cache = QtWidgets.QTableWidget(self.centralwidget)
        self.inst_cache.setGeometry(QtCore.QRect(30, 220, 141, 421))
        self.inst_cache.setObjectName("inst_cache")
        self.inst_cache.setColumnCount(2)
        self.inst_cache.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.inst_cache.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inst_cache.setHorizontalHeaderItem(1, item)
        self.inst_cache_t = QtWidgets.QLabel(self.centralwidget)
        self.inst_cache_t.setGeometry(QtCore.QRect(30, 190, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.inst_cache_t.setFont(font)
        self.inst_cache_t.setStyleSheet("")
        self.inst_cache_t.setAlignment(QtCore.Qt.AlignCenter)
        self.inst_cache_t.setObjectName("inst_cache_t")
        self.control_t = QtWidgets.QLabel(self.centralwidget)
        self.control_t.setGeometry(QtCore.QRect(30, 80, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.control_t.setFont(font)
        self.control_t.setStyleSheet("")
        self.control_t.setAlignment(QtCore.Qt.AlignCenter)
        self.control_t.setObjectName("control_t")
        self.control = QtWidgets.QTableWidget(self.centralwidget)
        self.control.setGeometry(QtCore.QRect(40, 110, 121, 61))
        self.control.setObjectName("control")
        self.control.setColumnCount(2)
        self.control.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.control.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.control.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.control.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.control.setHorizontalHeaderItem(1, item)
        View.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(View)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 24))
        self.menuBar.setObjectName("menuBar")
        self.load_file_2 = QtWidgets.QMenu(self.menuBar)
        self.load_file_2.setObjectName("load_file_2")
        View.setMenuBar(self.menuBar)
        self.choose_file = QtWidgets.QAction(View)
        self.choose_file.setObjectName("choose_file")
        self.load_file_2.addAction(self.choose_file)
        self.menuBar.addAction(self.load_file_2.menuAction())

        self.retranslateUi(View)
        QtCore.QMetaObject.connectSlotsByName(View)

    def retranslateUi(self, View):
        _translate = QtCore.QCoreApplication.translate
        View.setWindowTitle(_translate("View", "View"))
        self.title.setText(_translate("View", "Tomasulo\'s Simulator"))
        self.clock_btn.setText(_translate("View", "Clock"))
        item = self.inst_cache.horizontalHeaderItem(0)
        item.setText(_translate("View", "Addr"))
        item = self.inst_cache.horizontalHeaderItem(1)
        item.setText(_translate("View", "Instruction"))
        self.inst_cache_t.setText(_translate("View", "Instruction Cache"))
        self.control_t.setText(_translate("View", "Control"))
        item = self.control.verticalHeaderItem(0)
        item.setText(_translate("View", "Clock"))
        item = self.control.verticalHeaderItem(1)
        item.setText(_translate("View", "PC"))
        item = self.control.horizontalHeaderItem(0)
        item.setText(_translate("View", "New Column"))
        item = self.control.horizontalHeaderItem(1)
        item.setText(_translate("View", "Value"))
        self.load_file_2.setTitle(_translate("View", "Load File"))
        self.choose_file.setText(_translate("View", "Choose File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    View = QtWidgets.QMainWindow()
    ui = Ui_View()
    ui.setupUi(View)
    View.show()
    sys.exit(app.exec_())
